import request from '@/utils/request'

export const getTeaDashboard = () => request({ url: '/admin/tea/dashboard', method: 'get' })
export const listTeaProducts = (params) => request({ url: '/admin/tea/products', method: 'get', params })
export const listTeaCategories = () => request({ url: '/admin/tea/products/categories', method: 'get' })
export const addTeaProduct = (data) => request({ url: '/admin/tea/products', method: 'post', data })
export const updateTeaProduct = (id, data) => request({ url: `/admin/tea/products/${id}`, method: 'put', data })
export const delTeaProduct = (id) => request({ url: `/admin/tea/products/${id}`, method: 'delete' })
export const listTeaOrders = (params) => request({ url: '/admin/tea/orders', method: 'get', params })
export const updateTeaOrder = (id, data) => request({ url: `/admin/tea/orders/${id}`, method: 'put', data })
export const listTeaMembers = (params) => request({ url: '/admin/tea/members', method: 'get', params })
export const addTeaMember = (data) => request({ url: '/admin/tea/members', method: 'post', data })
export const updateTeaMember = (id, data) => request({ url: `/admin/tea/members/${id}`, method: 'put', data })
export const listTeaNotices = (params) => request({ url: '/admin/tea/notices', method: 'get', params })
export const addTeaNotice = (data) => request({ url: '/admin/tea/notices', method: 'post', data })
export const updateTeaNotice = (id, data) => request({ url: `/admin/tea/notices/${id}`, method: 'put', data })
export const delTeaNotice = (id) => request({ url: `/admin/tea/notices/${id}`, method: 'delete' })
export const listTeaAuctions = (params) => request({ url: '/admin/tea/auctions', method: 'get', params })
export const addTeaAuction = (data) => request({ url: '/admin/tea/auctions', method: 'post', data })
export const updateTeaAuction = (id, data) => request({ url: `/admin/tea/auctions/${id}`, method: 'put', data })
export const cancelTeaAuction = (id) => request({ url: `/admin/tea/auctions/${id}`, method: 'delete' })
export const consignAllTea = () => request({ url: '/admin/tea/warehouse/consign-all', method: 'put', data: {} })
export const getTeaStatement = (date) => request({ url: '/admin/tea/ledger', method: 'get', params: { view: 'statement', date } })
